apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: topics.kafkapilot.io
spec:
  group: kafkapilot.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replications:
                  type: integer
                  description: "Number of topic replications"
                  minimum: 1
                partitions:
                  type: integer
                  description: "Number of topic partitions"
                  minimum: 1
              required:
                - replications
                - partitions
  scope: Namespaced
  names:
    plural: topics
    singular: topic
    kind: Topic